### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by goggle** [goggle/plugin.video.swiplaytv#1]
- [x] Change icon `resources/icon.png`
- [x] Change fanart `resources/fanart.png`
- [x] Change YouTube icon `resources/media/icon_youtube.png`
- [x] Take screenshots and add them to the repository
- [x] Edit README
- [x] Edit `addon.xml`
